branches:
  only:
    - latest
    - next
    - unstable
language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
install: npm install
script:
  - yarn ensureLinted
  - yarn ensureFormatted
  - yarn test
  - yarn build
after_script:
  - yarn coverage | coveralls
