on:
  pull_request:
    branches:
      - v6
  push:
    branches:
      - v6
name: CI
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # `yarn install`
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: bootstrap # `yarn bootstrap`
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint # `yarn lint`
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # `yarn build`
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test # `yarn test`
