name: Snyk Code Security

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  open-source:
    name: '🔒 Open Source Scan'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - run: yarn
      - run: yarn install

      - uses: actions/checkout@v2
      - name: Run Snyk to check for known vulnerabilities in software supply chain
        uses: snyk/actions/node@0e928f3e9ae859e2b95ac2b89af55d7b6434244d
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        with:
          command: test
          args: --severity-threshold=medium --all-projects